//! # Watermark Validator / Verifier
//!
//! Provides integrity verification of extracted watermark hashes against expected
//! values recorded on the ledger.
//!
//! ## Verification Logic
//!
//! Two hash comparison modes are supported:
//!
//! | Mode | Use case |
//! |------|----------|
//! | **Exact match** | The extracted hash must equal the ledger hash byte-for-byte |
//! | **Payload MAC verify** | Re-derive the expected hash from the raw payload + identities |
//!
//! Both modes use constant-time comparison to prevent timing-based hash oracle attacks.

use sha2::{Digest, Sha256};

use crate::types::WatermarkError;

/// Concrete watermark integrity verifier.
pub struct WatermarkValidator;

impl WatermarkValidator {
    /// Verify that `extracted_hash` matches `expected_hash` using constant-time comparison.
    ///
    /// Both hashes must be lowercase hex-encoded SHA-256 digests (64 characters).
    ///
    /// # Returns
    /// `Ok(true)` on match, `Ok(false)` on mismatch (valid forensic result — wrong recipient),
    /// `Err(WatermarkError::VerificationFailed)` if either hash is malformed.
    pub fn verify(extracted_hash: &str, expected_hash: &str) -> Result<bool, WatermarkError> {
        // ── Validate format ────────────────────────────────────────────────────
        if extracted_hash.len() != 64 {
            return Err(WatermarkError::VerificationFailed(format!(
                "extracted_hash length {} ≠ 64 (expected lowercase hex SHA-256)",
                extracted_hash.len()
            )));
        }
        if expected_hash.len() != 64 {
            return Err(WatermarkError::VerificationFailed(format!(
                "expected_hash length {} ≠ 64 (expected lowercase hex SHA-256)",
                expected_hash.len()
            )));
        }

        // ── Decode hex ─────────────────────────────────────────────────────────
        let extracted_bytes = hex::decode(extracted_hash).map_err(|e| {
            WatermarkError::VerificationFailed(format!("extracted_hash hex decode error: {e}"))
        })?;
        let expected_bytes = hex::decode(expected_hash).map_err(|e| {
            WatermarkError::VerificationFailed(format!("expected_hash hex decode error: {e}"))
        })?;

        // ── Constant-time comparison ───────────────────────────────────────────
        // XOR all bytes and OR the result; any mismatch propagates to a non-zero accumulator.
        let matches = constant_time_eq(&extracted_bytes, &expected_bytes);
        Ok(matches)
    }

    /// Compute the expected watermark hash from a raw 142-byte payload.
    ///
    /// Useful when the verifier wants to recompute the hash rather than trust
    /// a hash transmitted over a channel.
    pub fn hash_from_payload(raw_payload: &[u8]) -> String {
        hex::encode(Sha256::digest(raw_payload))
    }

    /// Full attribution report: verify hash AND confirm payload HMAC is valid.
    ///
    /// This is the forensic-grade verification that confirms:
    /// 1. The hash of the extracted payload matches the ledger entry.
    /// 2. The payload's own HMAC tag is valid for the given identities
    ///    (proving the payload was generated by this system and not forged).
    pub fn verify_with_attribution(
        raw_payload: &[u8],
        expected_hash: &str,
        recipient_id: &str,
        document_id: &str,
        session_id: &str,
    ) -> Result<AttributionResult, WatermarkError> {
        use crate::payload::verify_payload_mac;

        // Step 1: Hash verification
        let computed_hash = Self::hash_from_payload(raw_payload);
        let hash_ok = Self::verify(&computed_hash, expected_hash)?;

        // Step 2: HMAC/MAC verification
        let mac_ok = verify_payload_mac(raw_payload, recipient_id, document_id, session_id);

        Ok(AttributionResult {
            hash_matches:   hash_ok,
            mac_valid:      mac_ok,
            computed_hash,
            verdict: match (hash_ok, mac_ok) {
                (true, true)  => AttributionVerdict::ConfirmedMatch,
                (true, false) => AttributionVerdict::HashMatchMacInvalid,
                (false, true) => AttributionVerdict::HashMismatchMacValid,
                (false, false)=> AttributionVerdict::NoMatch,
            },
        })
    }
}

/// The result of a full forensic attribution verification.
#[derive(Debug, Clone)]
pub struct AttributionResult {
    /// Whether the extracted hash equals the expected ledger hash.
    pub hash_matches: bool,
    /// Whether the raw payload's HMAC tag is valid for the given identities.
    pub mac_valid: bool,
    /// The SHA-256 hash computed from the raw payload.
    pub computed_hash: String,
    /// Human-readable forensic verdict.
    pub verdict: AttributionVerdict,
}

/// Forensic verdict from [`WatermarkValidator::verify_with_attribution`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AttributionVerdict {
    /// Both hash and MAC verified — strong positive forensic attribution.
    ConfirmedMatch,
    /// Hash matches but MAC is invalid — possible payload replay / tampering.
    HashMatchMacInvalid,
    /// MAC is valid but hash doesn't match ledger — payload from a different session.
    HashMismatchMacValid,
    /// Neither hash nor MAC matched — no forensic attribution possible.
    NoMatch,
}

// ──────────────────────────────────────────────────────────────────────────────
// Constant-time comparison
// ──────────────────────────────────────────────────────────────────────────────

/// Constant-time equality check for two byte slices.
/// Returns `true` iff `a == b` without short-circuiting.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut acc = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        acc |= x ^ y;
    }
    acc == 0
}

// ──────────────────────────────────────────────────────────────────────────────
// Unit tests
// ──────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sha256_hex(data: &[u8]) -> String {
        hex::encode(Sha256::digest(data))
    }

    #[test]
    fn verify_returns_true_for_matching_hashes() {
        let h = sha256_hex(b"test-payload");
        assert_eq!(WatermarkValidator::verify(&h, &h).unwrap(), true);
    }

    #[test]
    fn verify_returns_false_for_mismatched_hashes() {
        let h1 = sha256_hex(b"payload-a");
        let h2 = sha256_hex(b"payload-b");
        assert_eq!(WatermarkValidator::verify(&h1, &h2).unwrap(), false);
    }

    #[test]
    fn verify_errors_on_malformed_hash() {
        let err = WatermarkValidator::verify("not-a-hash", &sha256_hex(b"x"));
        assert!(matches!(err, Err(WatermarkError::VerificationFailed(_))));
    }

    #[test]
    fn hash_from_payload_is_deterministic() {
        let payload = b"test payload bytes";
        let h1 = WatermarkValidator::hash_from_payload(payload);
        let h2 = WatermarkValidator::hash_from_payload(payload);
        assert_eq!(h1, h2);
    }

    #[test]
    fn constant_time_eq_correct() {
        assert!( constant_time_eq(b"abc", b"abc"));
        assert!(!constant_time_eq(b"abc", b"abd"));
        assert!(!constant_time_eq(b"ab",  b"abc"));
    }

    #[test]
    fn attribution_verdict_confirmed_on_valid_payload() {
        use crate::payload::build_payload;
        use crate::types::CreateWatermarkParams;

        let params = CreateWatermarkParams {
            document_id: "d".to_string(), recipient_id: "r".to_string(),
            session_id: "s".to_string(), strength_factor: 1.0,
        };
        let raw = build_payload(&params, 12345).unwrap();
        let expected_hash = WatermarkValidator::hash_from_payload(&raw);

        let result = WatermarkValidator::verify_with_attribution(
            &raw, &expected_hash, "r", "d", "s",
        ).unwrap();
        assert_eq!(result.verdict, AttributionVerdict::ConfirmedMatch);
    }
}
