[package]
name = "watermark"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
shared     = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
anyhow     = { workspace = true }
hex        = { workspace = true }
uuid       = { workspace = true }
sha2       = { workspace = true }
rand       = { workspace = true }
chrono     = { workspace = true }
hmac       = "0.12"

[dev-dependencies]
shared = { workspace = true }
